version: "3"

services:
  db:
    image: postgres:16.3-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=edo_db
    restart: always
  api:
    build: ./api
    ports:
      - "5050:5000"
    restart: always
    depends_on:
      - db
