version: "3"

services:
  db:
    image: postgres:16.3-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=edo_db
    restart: always
    networks:
      - app-network

  cache:
    image: redis:7.2.5
    ports:
      - "6379:6379"
    volumes:
      - ./data/cache-data:/data
    networks:
      - app-network

  api:
    build: ./api
    ports:
      - "5050:5000"
    restart: always
    depends_on:
      - db
    networks:
      - app-network

  web-crawler:
    build: ./web-crawler
    depends_on:
      - db
      - cache
    volumes:
      - ./data:/app/data
    networks:
      - app-network
  
  pgadmin:
    image: dpage/pgadmin4:8.9
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_CONFIG_SERVER_HOST="db"
      - PGADMIN_CONFIG_SERVER_PORT=5432
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
    ports:
      - "6060:80"
    networks:
      - app-network
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/db  # Persist Redis Insight configuration
    depends_on:
      - cache
    networks:
      - app-network
    command: redisinsight
    restart: always
    environment:
      - REDISINSIGHT_PASSWORD=password

networks:
  app-network:
    driver: bridge

volumes:
  pgadmin_data:
    driver: local
  redis_insight_data:
