version: "3"

services:
  db:
    image: postgres:16.3-alpine3.20
    ports:
      - 5432:5432
    volumes:
      #- ./data:/var/lib/postgresql/data
      - ./api/model/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=edo_db
    restart: always
    networks:
      - app-network

  api:
    build: ./api
    ports:
      - "5050:5000"
    restart: always
    depends_on:
      - db
    networks:
      - app-network
  
  pgadmin:
    image: dpage/pgadmin4:8.9
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_CONFIG_SERVER_HOST="db"
      - PGADMIN_CONFIG_SERVER_PORT=5432
    ports:
      - "6060:80"
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge
