CREATE TABLE IF NOT EXISTS edos (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    mobileNumber VARCHAR(50),
    email VARCHAR(50),
    physicalAddress VARCHAR(50),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);
